### ISSUE TITLE
~svg-elements

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#595] opened 2016-02-06 16:36 UTC
To avoid breaking layouts when svgs are included inline, html5shiv can be called, but with a list of tagNames for svg passed in. Given the current implementation of html5shiv & polyfill.io's dependency resolving it may well be impossible to polyfill svg-elements but not html-elements _unless_ the shiv is included twice, so that needs a decision.

Also I notice html5shiv has the side effect of setting `window.html5`. Should we aim to suppress this?

**Comment by JakeChampion** [comment] 2016-03-17 22:20
Is this a duplicate of #519 / #531 ?

**Comment by wheresrhys** [comment] 2016-03-18 08:45
Nope. This is about inline svg

On Friday, 18 March 2016, Andrew Betts notifications@github.com wrote:

> Assigned #595
> https://github.com/Financial-Times/polyfill-service/issues/595 to
> @wheresrhys https://github.com/wheresrhys.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/polyfill-service/issues/595#event-594411622

## 

---

_This email was sent by a company owned by Financial Times Group Limited 
("FT Group http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law._

**Comment by triblondon** [comment] 2016-05-01 14:48
`window.html5` is annoying but I guess we'll live with it.  I suppose the simple answer here is to modify the html5-elements polyfill to invoke html5shiv with 'svg' added to `tagNames`, or suggest that it be added in html5shiv by default?

We're entering the twilight of people caring about IE8, so unless this causes sites to be unusable in IE8, I think it's probably not worth it.  @wheresrhys does FT need this?  If so can you add the FT label?

**Comment by wheresrhys** [comment] 2016-05-03 08:17
Not currently.

It can cause sites to be pretty unusable in IE8 e.g. in the previous incarnation of o-header the inline svg used for the logo caused a lot of layout breakages. But conditional comments offer a way round the problem

**Comment by triblondon** [comment] 2016-05-03 10:35
OK, if someone wants to PR the svg element into html5shiv, I think that would be a great idea.  But no action on our side.

**Closed as completed by triblondon** 2016-05-03 10:35 UTC
