### ISSUE TITLE
Use Web Platform Tests Project for unit tests

### ISSUE THREAD

**Issue by hgl** [polyfillpolyfill/polyfill-service#370] opened 2015-04-03 08:34 UTC
[web-platform-tests](https://github.com/w3c/web-platform-tests) implements unit tests for many web specs.

We should leverage that instead of reinventing the wheel (its unit test are actually much more thorough). And for missing unit tests (e.g., it doesn't have `before()`, `after()` dom4 unit tests), we should contribute to it.

The benefit is that browser engines, (e.g., [gecko](https://github.com/mozilla/gecko-dev/tree/master/testing/web-platform)) actually use this project to do unit testing. So if we contribute to that project, we contribute directly to browser engines. And they also contribute unit tests when they implement new features.

It's a win-win situation.

I still didn't take the time to get familiar with how its test runner works. I did ask about it at [public-test-infra@w3.org](https://lists.w3.org/Archives/Public/public-test-infra/2015JanMar/0018.html) a few months back, and the main maintainer pointed me to the [doc](http://wptrunner.readthedocs.org/en/latest/).

Not sure if you guys are interested in adopting it.

**Comment by hgl** [comment] 2015-04-03 08:44
And if you do want to adopt it, the way to test should also be changed.

We should serve the polyfills and _all_ unit tests to each browser, make sure the polyfills work cohesively. If a failing old browser passes all unit tests (can selectively disable some of them if turn out to be unpolyfillable) with the polyfills applied, we can be sure the polyfills are working correctly.

**Comment by triblondon** [comment] 2015-04-03 14:08
@juandopazo has some opinions on testing (see #326)

**Comment by hgl** [comment] 2015-04-03 14:27
test262 is the right choice for es unit tests, it's wonderful if we can use it.

web-platform-tests is for web APIs, it's python based though.

**Comment by juandopazo** [comment] 2015-04-03 15:24
We should totally make this happen. The how is a bit complicated. I guess I can create a grunt task that used the test262 harness. @hgl do you think these tests can be wrapped in a grunt task?

**Comment by hgl** [comment] 2015-04-11 05:23
@juandopazo sorry for the late reply. Did you ask can wpt be wrapped in a grunt task? I don't see the need. We just need to figure out a way to inject the polyfill code before the test code when starting its test runner.

I'm also wondering, how is the official test262 meant to be run? Can we directly inject the polyfill code to the original runner?

**Comment by triblondon** [comment] 2015-08-11 16:22
This is actually a duplicate of #235.

**Closed as completed by triblondon** 2015-08-11 16:22 UTC
