### ISSUE TITLE
Polyfill 3.17.0 service update - UIWebView on IOS stopped loading

### ISSUE THREAD

**Issue by matt-ville** [polyfillpolyfill/polyfill-service#1121] opened 2017-03-15 21:36 UTC
Hi,

I hope you may be able to help.

We are using webviews within a native IOS app, using UIWebView. We have a live app and have been using your service for polyfills for about 6 months with no problem (we run reactJS as the primary js library). Today we have started seeing users fail to load pages. I'm getting the app developer to try and get more info, as i realise i'm not giving you much to go on.

Just wondered if there could be anything in the latest release that could unsettle IOS UIWebView on IOS10? As out problems seemed to coincide with your release, but it could just be coincidence!

Thanks in advance for any help,

Regards,

Matt

**Comment by lepture** [comment] 2017-03-16 02:34
Same here.

**Comment by lepture** [comment] 2017-03-16 07:58
@matt-ville What is your App's User Agent?

**Comment by rubencodes** [comment] 2017-03-16 19:33
So, not sure if this is related, but it seems like more than a coincidence... My Electron web app broke yesterday, too, due to its User Agent being identified as "unknown". As stated above, it had been working successfully until around middle of yesterday. The user agent is:

`UA detected: electron/1.4.0 (unknown/unsupported; using policy `unknown=polyfill`)`

Should I split this off into a separate issue?

**Comment by JakeChampion** [comment] 2017-03-16 19:48
Please open a new issue for the electron detection :-)

**Comment by triblondon** [comment] 2017-03-17 05:51
@matt-ville @lepture @rubencodes Thanks for reporting this.  First of all, if you have production sites relying on our CDN service it's a good idea to regularly run against our QA service in your CI or test environment so you can be warned if we release something that inadvertently breaks your app.  You can swap out `polyfill.io` or `cdn.polyfill.io` for `qa.polyfill.io` to get the QA service.  All our minor and major releases are made available in QA for 7 days before being promoted to production.

Obviously please don't use the QA service in production, it is not highly available.

Regarding this issue, we are ideally looking for the console log of the error that you're seeing, the UA string of the browser that is exhibiting the problem, and a reduced test case in JSBin.com that we can use to reproduce the problem on the affected browser.

**Comment by callumj** [comment] 2017-03-21 22:57
I think I have managed to reproduce this (see Safari debugger screenshot):

![screenshot 2017-03-21 15 56 43](https://cloud.githubusercontent.com/assets/112037/24174669/18d8733c-0e4f-11e7-8c90-554b830bb5d9.png)


The UA is being faked as `Mozilla/5.0 (iPhone; CPU iPhone OS 10_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B72`

**Comment by JakeChampion** [comment] 2017-03-21 23:14
@callumj This should be fixed in the next release of the service

**Comment by triblondon** [comment] 2017-03-27 01:48
@JakeChampion can you link the PR or issue in which we're tracking the solution?

**Comment by triblondon** [comment] 2017-04-24 16:49
PR is scheduled for release in 3.18

**Closed as completed by triblondon** 2017-04-24 16:49 UTC
