### ISSUE TITLE
Inheritance of events is broken on IE11

### ISSUE THREAD

**Issue by falsandtru** [polyfillpolyfill/polyfill-service#705] opened 2016-05-24 21:27 UTC
The following test was passed before using your polyfill.

Note: `ev` is a click event object.

```
IE 11.0.0 (Windows 7 0.0.0) Unit: lib/dom bind click FAILED
        AssertionError:   #

          assert(ev instanceof Event)
                 |  |          |
                 |  false      #function#
                 PointerEvent{}
```

**Comment by triblondon** [comment] 2016-05-30 06:56
@falsandtru hi, thanks for reporting this.  I don't recognise this test, is this a third party test suite?  Can you give us a live example URL at which to run the test?  We ideally are looking for a test that includes only code from our service and as little code as possible to reproduce the issue.

**Comment by falsandtru** [comment] 2016-05-30 07:40
Thanks for replying. Here is a test. Can you repro?

Note: I'm using Mocha and power-assert for tests.

``` ts
    it('click', done => {
      const a = document.createElement('a');
      a.addEventListener('click', ev => {
        assert(ev instanceof Event);
        done();
      });
      document.createDocumentFragment().appendChild(a);
      a.click();
    });
```

**Comment by triblondon** [comment] 2016-05-30 07:56
That really doesn't give me all the info I need.  For example I don't know what polyfills you're loading.  A live test URL is the best way for me to help you here.  Could you use a tool like JSBin to demo the problem?

**Comment by falsandtru** [comment] 2016-05-30 08:12
Okay. http://jsbin.com/ludihajufu/1/edit?html,console

**Comment by triblondon** [comment] 2016-05-31 07:47
Ah, OK. So in IE11, the `Event` object is not a constructor, so you can't do `new Event`. This is fixed by the polyfill, but a side effect is that because it redefines `Event`, the prototype chain between constructors that inherit from Event and the Event object is broken, so your PointerEvent instance is no longer an instance of Event.  I think I can fix this with https://github.com/Financial-Times/polyfill-service/pull/713.

What do you think?

**Comment by falsandtru** [comment] 2016-05-31 14:30
It works fine :+1:

**Closed as completed** 2016-06-08 07:55 UTC
