### ISSUE TITLE
Not able to successfully build polyfill-service

### ISSUE THREAD

**Issue by aniket-gangadharan** [polyfillpolyfill/polyfill-service#2318] opened 2020-07-14 17:43 UTC
Not able to successfully build polyfill-service.
Hi,
The instructions mentioned in CONTRIBUTING.md was followed:
```shell
$ git clone https://github.com/Financial-Times/polyfill-service.git
$ cd polyfill-service
$ npm ci
$ npm run build # build the assets for the website
$ npm start # start a server on localhost:8080
```
But whenever I am building the application and executing the second last step i.e. "npm run build" I am getting error. The npm log is attached below:

/opt/polyfill-service# npm run build

> polyfill-service@4.28.1 build /opt/polyfill-service
> run-s clean eleventy build:*

> polyfill-service@4.28.1 clean /opt/polyfill-service
> rimraf ./dist ./.cache

> polyfill-service@4.28.1 eleventy /opt/polyfill-service
> eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering 11ty.js template ./src/assets/v3/library.11ty.js

`TemplateContentRenderError` was thrown
> ENOENT: no such file or directory, open '/opt/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/aliases.json'

`Error` was thrown:
    Error: ENOENT: no such file or directory, open '/opt/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/aliases.json'
Benchmark (Data): `./src/data/polyfills.js` took 575ms (51.9%)
Using pathPrefix: /v3
Copied 9 files / Wrote 0 files in 0.91 seconds (v0.11.0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polyfill-service@4.28.1 eleventy: `eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polyfill-service@4.28.1 eleventy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T17_39_41_666Z-debug.log
ERROR: "eleventy" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polyfill-service@4.28.1 build: `run-s clean eleventy build:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polyfill-service@4.28.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T17_39_41_701Z-debug.log

**Comment by JakeChampion** [comment] 2020-07-14 22:30
Hi @aniket-gangadharan, sorry to see the project is not building for you, hopefully we can help solve this.

I'm not sure what the issue is but maybe I can replicate it by using the same setup as yourself:
What version of node did you use? `node -v` will output the version
What version of npm did you use? `npm iv` will output the version
Do you have npm setup to ignore postinstall scripts? `npm config get` will output the config

Hopefully with that information we can figure out the issue 👍 

I ran the same commands as you on node v14.4.0 and npm 6.14.5 and all worked for me, here is the output of all the commands:
<details><summary>click here to view the output</summary>
```
❯ git clone https://github.com/Financial-Times/polyfill-service.git && cd polyfill-service && npm ci && npm run build && npm startCloning into 'polyfill-service'...
remote: Enumerating objects: 25, done.remote: Counting objects: 100% (25/25), done.remote: Compressing objects: 100% (25/25), done.
remote: Total 35905 (delta 16), reused 0 (delta 0), pack-reused 35880
Receiving objects: 100% (35905/35905), 24.51 MiB | 6.35 MiB/s, done.
Resolving deltas: 100% (23061/23061), done.

> core-js@2.6.11 postinstall /Users/jake.champion/polyfill-service/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/jake.champion/polyfill-service/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> fsevents@1.2.13 install /Users/jake.champion/polyfill-service/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jake.champion/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/jake.champion/.nvm/versions/node/v14.4.0/bin/node" "/Users/jake.champion/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jake.champion/polyfill-service/node_modules/fsevents
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> polyfill-library@3.28.1 postinstall /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.28.1
> npm run build


> polyfill-library@3.28.1 build /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.28.1
> npm run clean && node tasks/node/updatesources && node tasks/node/buildsources


> polyfill-library@3.28.1 clean /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.28.1
> rimraf ./polyfills/__dist

Updating third-party polyfills...
_TypedArray: New polyfill
  from ../js-polyfills/typedarray.js
~html5-elements: New polyfill
  from ../html5shiv/dist/html5shiv.min.js
atob: New polyfill
  from ../Base64/base64.js
AudioContext: New polyfill
  from ../audio-context-polyfill/AudioContext.js
EventSource: New polyfill
  from node_modules/event-source-polyfill/eventsource.js
fetch: New polyfill
  from node_modules/whatwg-fetch/fetch.js
 * Running module-specific update task update.task.js
HTMLPictureElement: New polyfill
  from ../picturefill/dist/picturefill.min.js
  from ../picturefill/dist/plugins/mutation/pf.mutation.min.js
Intl: New polyfill
  from ../intl/dist/Intl.min.js
 * Running module-specific update task update.task.js
Importing Intl.~locale.* polyfill from /Users/jake.champion/polyfill-service/node_modules/intl/locale-data/jsonp
716 imported locales
Intl polyfill imported successfully
JSON: New polyfill
  from ../json3/lib/json3.js
MutationObserver: New polyfill
  from ../mutationobserver-shim/MutationObserver.js
Promise: New polyfill
  from node_modules/yaku/dist/yaku.browser.global.min.js
UserTiming: New polyfill
  from ../usertiming/src/usertiming.js
WebAnimations: New polyfill
  from ../web-animations-js/web-animations.min.js
Polyfills updated successfully
Writing compiled polyfill sources to /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.28.1/polyfills/__dist/...
Waiting for files to be written to disk...
Sources built successfully

> polyfill-library@3.27.4 postinstall /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.27.4
> npm run build


> polyfill-library@3.27.4 build /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.27.4
> npm run clean && node tasks/node/updatesources && node tasks/node/buildsources


> polyfill-library@3.27.4 clean /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.27.4
> rimraf ./polyfills/__dist

Updating third-party polyfills...
_TypedArray: New polyfill
  from ../js-polyfills/typedarray.js
~html5-elements: New polyfill
  from ../html5shiv/dist/html5shiv.min.js
atob: New polyfill
  from ../Base64/base64.js
AudioContext: New polyfill
  from ../audio-context-polyfill/AudioContext.js
EventSource: New polyfill
  from node_modules/event-source-polyfill/eventsource.js
fetch: New polyfill
  from node_modules/whatwg-fetch/fetch.js
 * Running module-specific update task update.task.js
HTMLPictureElement: New polyfill
  from ../picturefill/dist/picturefill.min.js
  from ../picturefill/dist/plugins/mutation/pf.mutation.min.js
Intl: New polyfill
  from ../intl/dist/Intl.min.js
 * Running module-specific update task update.task.js
Importing Intl.~locale.* polyfill from /Users/jake.champion/polyfill-service/node_modules/intl/locale-data/jsonp
716 imported locales
Intl polyfill imported successfully
JSON: New polyfill
  from ../json3/lib/json3.js
MutationObserver: New polyfill
  from ../mutationobserver-shim/MutationObserver.js
Promise: New polyfill
  from node_modules/yaku/dist/yaku.browser.global.min.js
UserTiming: New polyfill
  from ../usertiming/src/usertiming.js
WebAnimations: New polyfill
  from ../web-animations-js/web-animations.min.js
Polyfills updated successfully
Writing compiled polyfill sources to /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/...
Waiting for files to be written to disk...
Sources built successfully

> polyfill-library@3.25.1 postinstall /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.25.1
> npm run build


> polyfill-library@3.25.1 build /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.25.1
> npm run clean && node tasks/node/updatesources && node tasks/node/buildsources


> polyfill-library@3.25.1 clean /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.25.1
> rimraf ./polyfills/__dist

Updating third-party polyfills...
_TypedArray: New polyfill
  from node_modules/js-polyfills/typedarray.js
~html5-elements: New polyfill
  from ../html5shiv/dist/html5shiv.min.js
of: No change
atob: New polyfill
  from node_modules/Base64/base64.js
AudioContext: New polyfill
  from ../audio-context-polyfill/AudioContext.js
EventSource: New polyfill
  from node_modules/event-source-polyfill/eventsource.js
fetch: New polyfill
  from node_modules/whatwg-fetch/fetch.js
 * Running module-specific update task update.task.js
HTMLPictureElement: New polyfill
  from node_modules/picturefill/dist/picturefill.min.js
  from node_modules/picturefill/dist/plugins/mutation/pf.mutation.min.js
Intl: New polyfill
  from ../intl/dist/Intl.min.js
 * Running module-specific update task update.task.js
Importing Intl.~locale.* polyfill from /Users/jake.champion/polyfill-service/node_modules/intl/locale-data/jsonp
716 imported locales
Intl polyfill imported successfully
JSON: New polyfill
  from node_modules/json3/lib/json3.js
MutationObserver: New polyfill
  from ../mutationobserver-shim/MutationObserver.js
Promise: New polyfill
  from node_modules/yaku/dist/yaku.browser.global.min.js
fromCodePoint: Polyfill updated, replacing old version
  from ../string.fromcodepoint/fromcodepoint.js
 * Running module-specific update task update.task.js
URL: New polyfill
  from node_modules/js-polyfills/url.js
UserTiming: New polyfill
  from ../usertiming/src/usertiming.js
WebAnimations: New polyfill
  from node_modules/web-animations-js/web-animations.min.js
Polyfills updated successfully
Writing compiled polyfill sources to /Users/jake.champion/polyfill-service/node_modules/polyfill-library-3.25.1/polyfills/__dist/...
Waiting for files to be written to disk...
Sources built successfully

> nodemon@2.0.4 postinstall /Users/jake.champion/polyfill-service/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


> esbuild@0.6.2 postinstall /Users/jake.champion/polyfill-service/node_modules/esbuild
> node install.js

+ esbuild-darwin-64@0.6.2
added 1 package in 1.468s

> polyfill-service@4.28.1 prepare /Users/jake.champion/polyfill-service
> npm run snyk-protect


> polyfill-service@4.28.1 snyk-protect /Users/jake.champion/polyfill-service
> snyk protect

Successfully applied Snyk patches

added 1885 packages in 85.239s

> polyfill-service@4.28.1 build /Users/jake.champion/polyfill-service
> run-s clean eleventy build:*


> polyfill-service@4.28.1 clean /Users/jake.champion/polyfill-service
> rimraf ./dist ./.cache


> polyfill-service@4.28.1 eleventy /Users/jake.champion/polyfill-service
> eleventy

Writing ./dist/v3/json/library-3.27.4.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.28.1.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.34.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.35.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.36.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.37.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.38.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.39.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.40.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.41.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.42.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.43.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.44.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.45.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.46.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.48.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.49.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.50.2.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.51.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.1.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.2.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/privacy-policy/index.html from ./src/assets/v3/privacy-policy.njk.
Writing ./dist/v3/api/index.html from ./src/assets/v3/api.njk.
Writing ./dist/v3/index.html from ./src/assets/v3/index.njk.
Writing ./dist/v3/security-policy/index.html from ./src/assets/v3/security-policy.njk.
Writing ./dist/v3/supported-browsers/index.html from ./src/assets/v3/supported-browsers.njk.
Writing ./dist/v3/report-a-bug/index.html from ./src/assets/v3/report-a-bug.njk.
Writing ./dist/v3/terms/index.html from ./src/assets/v3/terms.njk.
Writing ./dist/v3/packages/index.html from ./src/assets/v3/packages.njk.
Writing ./dist/v3/url-builder/index.html from ./src/assets/v3/url-builder.njk.
Using pathPrefix: /v3
Copied 9 files / Wrote 31 files in 20.04 seconds (646.5ms each, v0.11.0)

> polyfill-service@4.28.1 build:sass /Users/jake.champion/polyfill-service
> mkdir -p dist/css && sass src/assets/css/index.scss  --style=compressed --load-path=node_modules --load-path=node_modules/@financial-times | postcss --use autoprefixer --output dist/css/index.css --map

WARNING: oQuoteBase is deprecated: Use `oQuoteStandard` instead, or `oQuoteEditorial` if outputting an editorial-style quote.
    node_modules/@financial-times/o-quote/src/scss/_mixins.scss 5:2    oQuoteBase()
    node_modules/@financial-times/o-layout/src/scss/_mixins.scss 81:4  -oLayoutTypography()
    o-layout/main.scss 51:3                                            oLayout()
    src/assets/css/index.scss 55:1                                     root stylesheet

WARNING: oQuoteBaseCite is deprecated: Use `oQuoteStandardCite` instead, or `oQuoteEditorialCite` if outputting an editorial-style quote.
    node_modules/@financial-times/o-quote/src/scss/_mixins.scss 13:2   oQuoteBaseCite()
    node_modules/@financial-times/o-layout/src/scss/_mixins.scss 85:5  -oLayoutTypography()
    o-layout/main.scss 51:3                                            oLayout()
    src/assets/css/index.scss 55:1                                     root stylesheet


> polyfill-service@4.28.1 build:js /Users/jake.champion/polyfill-service
> mkdir -p dist/js && esbuild src/assets/js/index.js --bundle --minify > dist/js/index.min.js


> polyfill-service@4.28.1 start /Users/jake.champion/polyfill-service
> ./start_server.sh server/index.js

Started worker 1
Warning: metrics are not being recorded for this application. Please provide a FT_GRAPHITE_APP_UUID environment variable
Warning: errors are not being logged to Sentry for this application. Please provide a SENTRY_DSN environment variable
polyfill-service configured (graphite=false logging=true sentry=false)
polyfill-service started (env=development port=8080)
```
</details>

**Comment by aniket-gangadharan** [comment] 2020-07-15 03:56
Hi @JakeChampion 
Here are the versions and the config for npm:
/opt/polyfill-service# node -v
v14.5.0

/opt/polyfill-service# npm -v
6.14.5

/opt/polyfill-service# npm config get
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.5 node/v14.5.0 linux x64"
; node bin location = /usr/bin/node
; cwd = /opt/polyfill-service
; HOME = /root
; "npm config ls -l" to show all defaults.

Not sure if there is any impact of the OS but I am running this on machine with Debian 9.12

**Comment by JakeChampion** [comment] 2020-07-15 11:06
I'll try it on debian 9.12 and see if I can replicate the issue 👍

**Comment by JakeChampion** [comment] 2020-07-15 15:50
I can replicate the issue in debian 9.12 🎉 

These warnings during `npm ci` make me think the issue is something to do with npm postinstall scripts not working under debian:

```
npm WARN lifecycle polyfill-library@3.28.1~postinstall: cannot run in wd polyfill-library@3.28.1 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.28.1)
npm WARN lifecycle polyfill-library@3.27.4~postinstall: cannot run in wd polyfill-library@3.27.4 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.27.4)
npm WARN lifecycle polyfill-library@3.25.1~postinstall: cannot run in wd polyfill-library@3.25.1 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.25.1)
```

<details><summary>Terminal commands and output I used to replicate issue</summary>
```
docker run -it --volume ~/polyfill-service:/root/polyfill-service debian:9.12 /bin/bash
root:/# apt-get update && apt-get install curl
root:/# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
root:/# nvm install 14.5
root:/# node -v
v14.5.0
root:/# npm -v
6.14.5
root:/# cd ~/polyfill-service/
root:~/polyfill-service# npm ci
npm WARN lifecycle polyfill-library@3.28.1~postinstall: cannot run in wd polyfill-library@3.28.1 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.28.1)
npm WARN lifecycle polyfill-library@3.27.4~postinstall: cannot run in wd polyfill-library@3.27.4 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.27.4)
npm WARN lifecycle polyfill-library@3.25.1~postinstall: cannot run in wd polyfill-library@3.25.1 npm run build (wd=/root/polyfill-service/node_modules/polyfill-library-3.25.1)

added 1885 packages in 845.164s
root:~/polyfill-service# npm run build
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering 11ty.js template ./src/assets/v3/library.11ty.js

`TemplateContentRenderError` was thrown
> ENOENT: no such file or directory, open '/root/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/aliases.json'

`Error` was thrown:
    Error: ENOENT: no such file or directory, open '/root/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/aliases.json'
Benchmark (Data): `./src/data/polyfills.js` took 4004ms (62.3%)
Using pathPrefix: /v3
Copied 9 files / Wrote 0 files in 4.78 seconds (v0.11.0)
```
</details>

**Comment by JakeChampion** [comment] 2020-07-15 15:52
@aniket-gangadharan Are you running `npm ci` as the root user? If so npm will not run postinstall scripts unless you set `unsafe-perm` to true like so -- `npm set unsafe-perm true`.

**Comment by JakeChampion** [comment] 2020-07-15 16:17
I can confirm that if you were running as root, `npm set unsafe-perm true` resolves the issue:

```
root@49f288e17efe:~/polyfill-service# npm set unsafe-perm true
root@49f288e17efe:~/polyfill-service# npm ci
added 1885 packages in 1277.9s
root@49f288e17efe:~/polyfill-service# npm run build

> polyfill-service@4.28.1 build /root/polyfill-service
> run-s clean eleventy build:*


> polyfill-service@4.28.1 clean /root/polyfill-service
> rimraf ./dist ./.cache


> polyfill-service@4.28.1 eleventy /root/polyfill-service
> eleventy

Writing ./dist/v3/json/library-3.27.4.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.28.1.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.34.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.35.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.36.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.37.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.38.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.39.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.40.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.41.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.42.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.43.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.44.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.45.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.46.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.48.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.49.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.50.2.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.51.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.0.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.1.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/json/library-3.52.2.json from ./src/assets/v3/library.11ty.js.
Writing ./dist/v3/api/index.html from ./src/assets/v3/api.njk.
Writing ./dist/v3/report-a-bug/index.html from ./src/assets/v3/report-a-bug.njk.
Writing ./dist/v3/security-policy/index.html from ./src/assets/v3/security-policy.njk.
Writing ./dist/v3/index.html from ./src/assets/v3/index.njk.
Writing ./dist/v3/privacy-policy/index.html from ./src/assets/v3/privacy-policy.njk.
Writing ./dist/v3/supported-browsers/index.html from ./src/assets/v3/supported-browsers.njk.
Writing ./dist/v3/terms/index.html from ./src/assets/v3/terms.njk.
Writing ./dist/v3/url-builder/index.html from ./src/assets/v3/url-builder.njk.
Writing ./dist/v3/packages/index.html from ./src/assets/v3/packages.njk.
Benchmark (Data): `./src/data/polyfills.js` took 2643ms (8.5%)
Using pathPrefix: /v3
Copied 9 files / Wrote 31 files in 30.11 seconds (971.3ms each, v0.11.0)
> polyfill-service@4.28.1 build:js /root/polyfill-service
> mkdir -p dist/js && esbuild src/assets/js/index.js --bundle --minify > dist/js/index.min.js

root@49f288e17efe:~/polyfill-service# npm start

> polyfill-service@4.28.1 start /root/polyfill-service
> ./start_server.sh server/index.js
Warning: metrics are not being recorded for this application. Please provide a FT_GRAPHITE_APP_UUID environment variable
Warning: errors are not being logged to Sentry for this application. Please provide a SENTRY_DSN environment variable
polyfill-service configured (graphite=false logging=true sentry=false)
polyfill-service started (env=development port=8080)
```

**Comment by aniket-gangadharan** [comment] 2020-07-16 03:36
Hi @JakeChampion 
Thanks a lot for the help. I am able to build the polyfill-service.

**Comment by JakeChampion** [comment] 2020-07-16 10:34
Woo hoo! 🎉 

I'm very happy to hear that 😄 

I will now close this issue 👍

**Closed as completed by JakeChampion** 2020-07-16 10:34 UTC
Labels: discussion, service
