### ISSUE TITLE
Facebook in-app browser recognized as "facebook" instead of "mobile safari"

### ISSUE THREAD

**Issue by andreafdaf** [polyfillpolyfill/polyfill-service#697] opened 2016-05-11 17:38 UTC
While the UA in Facebook in-app browser for Android is correctly identified as "Chrome" in iOS it is recognized as "facebook"

This might be an issue with https://github.com/3rd-Eden/useragent so I'm opening an issue also there, then when this is fixed I'm going to PR with the updated useragent version

If you don't think it is an issue with useragent I'm going to PR with an alias from "facebook" to "ios_saf"

This all comes from this issue https://github.com/facebook/react/issues/6739 with the Intl polyfill

**Comment by triblondon** [comment] 2016-05-30 07:01
Duplicate of #561.  There's a solution proposed there, so please do submit a PR.  It would be much appreciated.

**Closed as completed by triblondon** 2016-05-30 07:01 UTC
