### ISSUE TITLE
Map and Set causing IE11 to break

### ISSUE THREAD

**Issue by victorwhy** [polyfillpolyfill/polyfill-service#715] opened 2016-05-31 18:20 UTC
Hi,

Recently (possibly with the new update), a couple pages on our app have started to have this error, specifically IE11.

![image](https://cloud.githubusercontent.com/assets/7387858/15685368/65db24e8-2739-11e6-9004-8ff71fa3a097.png)

When I took out the default features, and put in the features one by one, I found that it was `Map` and `Set` causing this error.

Anyone else having this issue?

We aren't using `Set` or `Map` on these pages, so unsure of what's actually causing this.

**Comment by JakeChampion** [comment] 2016-05-31 19:29
Yes, we are also seeing the issue on our sites. Our fix was to exclude the Symbol polyfill (which is required by Map and Set) by adding `&excludes=Symbol,Symbol.iterator,Symbol.species`. It is only a temporary fix whilst we investigate the issue in more detail.

Does this fix it for you?

**Comment by victorwhy** [comment] 2016-05-31 20:03
Huh, that seemed to have worked, yes.

I do get a `'Symbol' is undefined` error, however.

What I don't understand is why `Symbol` or any of those other features are getting included in the first places? according to the docs, `Symbol` isn't part of the default features?

But thanks for the help! Glad to hear that it's being worked on.

**Comment by JakeChampion** [comment] 2016-05-31 20:28
You are correct, Symbol is not in the default set directly but, Map and Set are dependant upon Symbol being present, if your browser has Symbol then the polyfill won't be included in the bundle from cdn.polyfill.io. However, there are no browsers which have Symbol and don't have Map or Set.

If you could find the piece of code in your application's JS which is surfacing the error that would help us a lot in our efforts on fixing this issue.

**Comment by victorwhy** [comment] 2016-05-31 21:22
I'm a little confused.  it looks like IE11 doesn't have Symbol natively, correct?  So how are `Map` and `Set` default for IE11?  if `Map` and `Set` are dependencies for `Symbol`, it should always be a default too, right?

**Comment by victorwhy** [comment] 2016-05-31 21:22
But I will poke around and see if we can find the code that's triggering this.

Thanks again for the help!

**Comment by victorwhy** [comment] 2016-06-01 15:57
@JakeChampion after a bit of searching, this piece of code that a contractor added to our codebase was causing this issue:

`NodeList.prototype[Symbol.iterator] = Array.prototype[Symbol.iterator];`

I think they were trying to make it easier to iterate over `NodeList` but there were better solutions that we already implemented and didn't take that line out! D:

Hope this helps!

**Comment by JakeChampion** [comment] 2016-06-01 16:32
Thanks, that definitely helps. I believe the underlying issue is the same as #690. @wheresrhys, could you confirm whether these issues are one and the same? If they are, I'm happy to close either issue.

**Comment by wheresrhys** [comment] 2016-06-01 16:38
Very closely related, but probably different. 

> I do get a 'Symbol' is undefined error, however.

suggests that perhaps core-js's `Symbol` polyfill isn't part of the problem here (unless the code that throws that is not babelifed whereas other code on the page is)

**Comment by nicomfe** [comment] 2016-06-01 23:03
My 2 cents here, we are using Polifill service v3.6.1 and were getting this error on IE11:

`Out Of stack space
File: polyfill.js, Line 1535, Column 4`

The workaround was to add this to the polyfill import as @JakeChampion said
&excludes=Map,Set,Symbol,Symbol.iterator,Symbol.species

We are not using Map and Set so adding this should also fix the "Symbol is undefined" errors

**Comment by robwierzbowski** [comment] 2016-07-04 21:36
Excluding Symbol and its dependencies as @nicomfe said definitely helps. I think `Map` and `Set` being default polyfills and requiring `Symbol` makes the issue more severe though. Like @victorwhy mentioned, excluding `Symbol` throws errors in the `Map` and `Set` polyfills on browsers that don't support `Symbol`.

Oddly, polyfill.io is serving the `Map` and `Set` polyfills to IE11, even though it supports `Map` and `Set`. So we're getting the `Symbol` error, but the code we have that uses `Map` and `Set` still works `:P`. 

![image](https://cloud.githubusercontent.com/assets/925735/16570124/7cd51912-420d-11e6-8894-94b6610e90e4.png)

**Comment by robwierzbowski** [comment] 2016-07-04 21:38
@JakeChampion, any updates on the `Symbol` polyfill? If it helps, I could try testing other OSS Symbol polyfills in IEs, not sure I have enough domain knowledge to debug the current one.

**Comment by robwierzbowski** [comment] 2016-07-04 21:59
Wondering if this issue (https://github.com/Financial-Times/polyfill-service/issues/679) is discussing the same problems, and if so if Map/Set/Symbol are fixed. Will test.

**Comment by wheresrhys** [comment] 2016-07-04 22:06
From working on this PR to implement array iterators https://github.com/Financial-Times/polyfill-service/pull/726, and which originally contained DOM collection iterators too, it looks like the problem is caused by attaching  `Symbol` to a DOM collection (as @victorwhy also points out above https://github.com/Financial-Times/polyfill-service/issues/715#issuecomment-223039151).

**Comment by robwierzbowski** [comment] 2016-07-08 22:18
Seems like this issue is just about inadvisably using `Symbol` to attach an iterator to a DOM collection. By removing the offending code, Polyfill.io works fine. Should we close this issue?

**Comment by triblondon** [comment] 2016-07-09 01:51
@robwierzbowski we serve Map and Set to IE11 because its native implementation is buggy/incomplete.

It seems like it's a common use case to attach an iterator to a DOM collection and if that works natively then the polyfill should not fall over if you try and do it.  I think it's worth trying to fix this issue, especially as it's still a problem for FT sites too.

**Comment by triblondon** [comment] 2016-07-11 07:32
Here's a JSBin that reproduces this problem:

http://jsbin.com/momuqi/edit?js,output

As we've established, this is a problem of attempting to attach an iterator to NodeList.prototype.  Since NodeLists appear to natively act as iterators in Chrome, I assume a full polyfill would cover this case, though I think we didn't polyfill this because it's outside the Symbol object.  @wheresrhys was planning to make those objects iterable.

**Comment by JakeChampion** [comment] 2016-07-28 20:06
I believe this issue has been resolved with the 3.8.1 release. @victorwhy, are you still seeing this problem?

**Comment by victorwhy** [comment] 2016-07-28 21:00
@JakeChampion haven't had a chance to test, but will check it out when I get some time! thanks!

**Comment by triblondon** [comment] 2016-08-03 04:08
Closing this on the basis that it is fixed in prod.  @victorwhy please feel free to post a followup with your results if it's not working for you.

**Closed as completed by triblondon** 2016-08-03 04:08 UTC
