### ISSUE TITLE
Allow generating a gated bundle to polyfill a specific set of browsers, not just one

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#1787] opened 2018-10-25 11:39 UTC
Nice to see this project is still improving all the time!

I have a scenario where I want to use the Polyfill Service library to generate my own bundle at build time, but it doesn't seem to expose the methods I need.

My scenario:

- I've got an inline `<script>` in my `<head>`, in which I inject a script element to load `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch`
- When that polyfill.io script fails to load for any reason, I want to inject a different script as a fallback: `/public/polyfill-fallback.js`
- This `polyfill-fallback.js` should be a static, pre-generated, **gated** polyfill bundle that makes the features `default,fetch` available in all the browsers I support.

To generate the fallback bundle, I can do something like this when building my app:

```js
const polyfillLibrary = require("polyfill-service");

const polyfillBundle = polyfillLibrary
  .getPolyfillString({
    unknown: "polyfill",
    minify: true,
    features: {
      default: { flags: ["gated"] },
      fetch: { flags: ["gated"] }
    }
  })
  .then(function(polyfills) {
    // [...save to "/public/polyfill-fallback.js"]
  });
});
```

(I can see there is a new polyfill-library package, but it seems to be pretty much the same API, I think.)

Let's say I want my fallback to work for these browsers: `last 2 chrome versions, ie 11, edge > 13`. The problem is the bundle will include polyfills for **all** features, even ones that don't actually need polyfilling in any of those browsers.

It's not clear how I can include just the polyfills I actually need to cover my list of supported browsers. The library only lets me provide a UA string, and only one at a time. I guess I could manually convert my browserslist query into a few UA strings (one for IE10, one for Edge 13, etc) but then it's not clear how I would collate these to get a single bundle.

Would you consider a PR for adding the option to specify a list of specific browser versions instead of a UA string?

**Comment by sheerun** [comment] 2018-12-13 15:57
Currently the standard for browser ranges is https://github.com/browserslist/browserslist 

Maybe this library could somehow integrate with it? @JakeChampion Is there any progress?

**Comment by JakeChampion** [comment] 2019-01-22 20:12
This looks to be a duplicate of #1691. Closing this issue in favour of tracking the feature request in one place.

**Closed as completed by JakeChampion** 2019-01-22 20:12 UTC
