### ISSUE TITLE
Uncaught TypeError: Expected a string in UC Browser Desktop

### ISSUE THREAD

**Issue by mikebridge** [polyfillpolyfill/polyfill-service#1702] opened 2018-04-17 15:25 UTC
When I use this in UC Browser Desktop 7.0.185.1002 on Windows 10:

```html
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Set&unknown=polyfill"></script>
```

I get this parsing error:

_edited with correct stacktrace_
```
index.js:7Uncaught TypeError: Expected a string
    at ./node_modules/escape-string-regexp/index.js.module.exports (index.js:7)
    at index.js:24
    at Array.forEach (polyfill.min.js?features=Set&unknown=polyfill:3)
    at index.js:23
    at Object.<anonymous> (index.js:34)
    at Object../node_modules/react-dev-utils/node_modules/chalk/index.js (index.js:116)
    at __webpack_require__ (bootstrap 7ad45be…:707)
    at fn (bootstrap 7ad45be…:112)
    at Object../node_modules/react-dev-utils/formatWebpackMessages.js (formatWebpackMessages.js:17)
    at __webpack_require__ (bootstrap 7ad45be…:707)
```

However, this parses fine:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en&unknown=polyfill"></script>
```

**Comment by JakeChampion** [comment] 2018-04-17 15:34
Thanks for the issue @mikebridge. Could you post the full user-agent string of the browser that generated this error please?

Also, are you aware that the stack trace lists a different polyfill.io url to the ones you posted in the issue? Did you narrow the issue down to `Set`?

**Comment by mikebridge** [comment] 2018-04-17 16:29
@JakeChampion Sorry, I just fixed the incorrectly copied-and-pasted stack trace.  I tried several random permutations among the six we're pulling in, and the only one that works is that last one.

I'd never heard of the UC Browser before last week, but apparently it's big in China and other parts of Asia, especially on mobile.  This is the [desktop version](http://www.ucweb.com/desktop/) I installed:

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 UBrowser/7.0.185.1002 Safari/537.36`

**Comment by mikebridge** [comment] 2018-04-17 16:34
... and the reason I discovered this issue is that I was using the "unknown=polyfill" workaround to [polyfill the mobile version of UCBrowser](https://github.com/Financial-Times/polyfill-service/issues/1079) and discovered that this causes the desktop version to break.

**Comment by mikebridge** [comment] 2018-04-17 16:51
@JakeChampion I see that this desktop version has "UBrowser" and my mobile version is has "UCBrowser", and neither of these is picked up by the `"uc browser"` alias in [UA.js](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/lib/UA.js).  Would it help if I created a PR to add better support for both these browsers?  It looks like this desktop version is based on Chrome 55 (not IE10).  The Android version also looks Chrome-like.

**Comment by mikebridge** [comment] 2018-04-19 23:31
I've been trying to get polyfill.io working on both UC Browser Mobile and Desktop without much success yet.   In the meantime, if it helps anyone else, there's a development version of the Android UC Browser [here](https://plus.ucweb.com/), and you can connect to it and debug it from desktop Chrome just like you would the mobile chrome browser.

I'm also experiencing the `escape-string-regexp` problem on mobile.

**Comment by JakeChampion** [comment] 2018-04-19 23:42
Hi @mikebridge, The user-agent string you posted gets detected by polyfill.io as `uc browser/7.0.0`, which is a version of uc browser we currently do not support. The only version that we've got support for is 9.9, which we alias over to IE 10, the reasoning behind the alias is documented in the [pull-request which added it](https://github.com/Financial-Times/polyfill-service/pull/853).

I don't know much about UC Browser, in fact, I never knew they had a desktop version! You mention that the desktop version looks like it is based off of Chrome 55, how did you come to this conclusion? If that is the case, we can look to add another alias for UBrowser to Chrome.

With regards to the actual error and stack trace you have posted, could you post a small amount of code that enables me to replicate the issue? It would help me greatly in figuring out what the issue is  that causes the errors you are seeing in your web page.

**Comment by mikebridge** [comment] 2018-04-20 16:10
@JakeChampion It occurs in that version of the desktop merely by including it---this alone reproduces it for me:

```
<!doctype html>
<html lang="en">
<head>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill"></script>
</head>
<body>
Hello
</body>
</html>
```

When I go to `Feedback and Help -> About` the desktop version contains the following text:

    UC Browser
    Version 7.0.185.1002 ...
    Chromium kernel version: 55.0.2883.87
    IE Kernel version 11.0.16299.371

The mobile version is apparently based on a modified webkit (https://www.quora.com/What-is-the-JavaScript-engine-used-behind-UC-Browser).

This error I'm seeing occurs in [this line in Chalk](https://github.com/chalk/chalk/blob/master/index.js#L56), which makes me think this error is a side-effect of another problem....

**Comment by JakeChampion** [comment] 2019-01-23 12:10
I believe this is now fixed in polyfill.io/v3 as we detect that the browser is one we do not support and so we wrap all the polyfills in feature detects. Please comment on this issue if you think the issue has not been resolved.

**Closed as completed by JakeChampion** 2019-01-23 12:10 UTC
