### ISSUE TITLE
what should be my babel config if i use polyfill.io 

### ISSUE THREAD

**Issue by awebdeveloper** [polyfillpolyfill/polyfill-service#1193] opened 2017-05-06 12:05 UTC
Please have a info on what our babel config be if i use polyfill.io

**Comment by pieterbeulque** [comment] 2017-06-05 14:18
Hey, could you elaborate on what you're trying to do? Using polyfill.io has no direct impact on your Babel usage.

You add polyfill.io first, then your transpiled code and serve both to the user.

```
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script src="bundle.js></script>
```

**Comment by awebdeveloper** [comment] 2017-06-07 08:35
using pollyfill negates the use of cable to a large extend but not entirely. It good to include in docs for what  all do i still need bable for .

**Comment by triblondon** [comment] 2017-06-07 08:51
Duplicate of https://github.com/Financial-Times/polyfill-service/issues/1099

**Closed as completed by triblondon** 2017-06-07 08:51 UTC
