### ISSUE TITLE
URL builder adds "-polyfill" suffix to all features

### ISSUE THREAD

**Issue by MattiasBuelens** [polyfillpolyfill/polyfill-service#1906] opened 2019-03-09 18:33 UTC
## What
The URL builder (https://cdn.polyfill.io/v3/url-builder/) appends a `-polyfill` suffix to every selected feature in the URL. These feature names are not recognized by the service, so it always returns empty polyfills for those URLs.

### Steps to reproduce
1. Go to the V3 URL builder: https://cdn.polyfill.io/v3/url-builder/
1. Select any feature (e.g. `Array.from`)
1. Observe the URL
1. Open the URL in a browser that needs a polyfill for that feature (e.g. Internet Explorer 11)

## Expected results
The generated URL is:
```
https://polyfill.io/v3/polyfill.js?features=Array.from
```
Opening it in an older browser serves the requested polyfill.

## Actual results
The generated URL is:
```
https://polyfill.io/v3/polyfill.js?features=Array.from-polyfill
```
Opening it in an older browser serves no polyfills.

![Screenshot](https://user-images.githubusercontent.com/649348/54075589-639e5700-42a1-11e9-9ac1-47e528bf398c.png)

**Comment by JakeChampion** [comment] 2019-03-11 11:04
This is now fixed, thanks for filing the issue :-)

**Closed as completed by JakeChampion** 2019-03-11 11:04 UTC

**Comment by MattiasBuelens** [comment] 2019-03-11 11:38
Thanks... but now "Filter polyfills" no longer works! 😅 

Should I file a new issue?

**Comment by JakeChampion** [comment] 2019-03-11 11:42
@MattiasBuelens Hmm, "Filter polyfills" works for me. How can I reproduce the issue you see?

![image](https://user-images.githubusercontent.com/1569131/54121551-ab80c380-43f2-11e9-986b-31398583a8e4.png)

![image](https://user-images.githubusercontent.com/1569131/54121562-b5a2c200-43f2-11e9-9875-34779df9558c.png)

**Comment by MattiasBuelens** [comment] 2019-03-11 17:20
@JakeChampion Weird. On my end, it doesn't work on any machine in any browser. 😕 

I did some digging. An `aria-hidden` attribute is set on the `<input type="checkbox">`, but that checkbox is always hidden anyway. It looks like the `aria-hidden` attrbite should have been set on the parent `<div class="polyfill">` instead.

![image](https://user-images.githubusercontent.com/649348/54143417-14376280-442a-11e9-87f8-fdf627ef2fb3.png)

...I really should have filed this as a separate issue. Sorry!

**Comment by petlys** [comment] 2019-03-18 08:31
This issue seems to be present again
