### ISSUE TITLE
PURGE cache after fixes deployed

### ISSUE THREAD

**Issue by callumj** [polyfillpolyfill/polyfill-service#577] opened 2016-01-13 22:31 UTC
The cache for certain UAs has not been purged since the fix for https://github.com/Financial-Times/polyfill-service/issues/572 was deployed.

Can we get a `PURGE` across the CDN so we don't run into cached empty responses?

```
» http GET "https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=es6,Intl.~locale.en|always"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 181142
Cache-Control: public, max-age=604800, stale-while-revalidate=604800, stale-if-error=604800
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 63
Content-Type: application/javascript; charset=utf-8
Date: Wed, 13 Jan 2016 22:26:01 GMT
Etag: W/"2d-o7gMCX6akln1e+RqzU7W9w"
Server: Cowboy
Timing-Allow-Origin: *
Vary: Accept-Encoding
Vary: User-Agent
Via: 1.1 vegur
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Served-By: cache-lax1432-LAX
X-Timer: S1452723961.904334,VS0,VE20

/* Unsupported UA detected: httpie/0.9.2 */

```

**Comment by jgeggatt** [comment] 2016-01-15 23:31
Hey guys, I've been running into this too - looks like a `PURGE` will get it fixed.  Any chance you guys could do that before the long weekend (please and thank you)?

**Comment by JakeChampion** [comment] 2016-01-16 17:58
I don't believe I have the privileges required to purge the cache. I've assigned @triblondon as I believe he will know who can do this for us.

**Comment by matthew-andrews** [comment] 2016-01-16 18:48
As a long term solution it would be good not to rely on purges …  Perhaps it would be better to reduce the cache to 48 hours from 1 week?

**Comment by callumj** [comment] 2016-01-16 19:01
The way we are getting around this now is to append a query param like `cache=EPOCH` where EPOCH could be a random number or UNIX time stamp baked into the HTML (so it doesn't change).

**Comment by triblondon** [comment] 2016-01-20 09:16
Whoops, sorry I didn't look at this at the time of the release.  It's now been almost 7 days so the issue is moot, but we can discuss what to do next time...

My preference is to just leave it as-is, and purge proactively if we need to.  Picking a different TTL is unlikely to satisfy everyone, and if we shorten the TTL to 2 days we need approximately double the number of backends.

Purging on deploy is an option, but it vastly increases the risks associated with deploys, and also we need to bear in mind that the service runs on infrastructure that cannot possibly handle the full load of public traffic if the whole CDN were to disappear. So we would need to deploy, scale out the number of nodes to handle the full brunt of traffic (go from 2 backends to maybe 50), then purge the cache, then scale them back again once the cache is re-primed.  That seems overly complicated vs simply waiting a week!

Obviously developers also have the option of a version query param, though I'm keeping an eye on this as it's also a DOS mechanism and we may want to strip all non-recognised query params at the CDN to guard against this risk.  Maybe if we do that we could shorten the TTL as a compromise?

**Comment by JakeChampion** [comment] 2016-01-20 11:28
Does Heroku offer any form of automated scaling that we could use? In previous projects I've used AWS and had the services scale automatically based on real-time load/cpu-usage/messages in a queue.

**Comment by triblondon** [comment] 2016-01-21 10:41
Well there's a third party service to do it: https://www.hirefire.io/.  I'm reluctant to acknowledge that this is a significant problem though. Currently we allow cache-busting query params, so as long as those are not abused there's always a solution for the impatient.

I'm inclined to close this - but will leave for a day or so for people to tell me how wrong I am.

**Closed as completed** 2016-01-30 11:19 UTC
