### ISSUE TITLE
As per #490 .defineProperty throws exception, but...

### ISSUE THREAD

**Issue by davidpelayo** [polyfillpolyfill/polyfill-service#712] opened 2016-05-30 15:21 UTC
When you include the [Intl polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/polyfill.js), this polyfill already uses `.defineProperty` with getter functions.
Therefore, although not having code with getter / setter codes, as described in #490, it's failing because I included Intl in the requested bundle.

Is there any Intl implementation over there without using `defineProperty`, or any other suggested solution?

**Comment by triblondon** [comment] 2016-05-31 03:25
There are actually very few examples of accessor properties being used in Intl.  I found three from a Github search:

https://github.com/andyearnshaw/Intl.js/blob/master/src/11.numberformat.js#L372
https://github.com/andyearnshaw/Intl.js/blob/master/src/12.datetimeformat.js#L787
https://github.com/andyearnshaw/Intl.js/blob/master/src/12.datetimeformat.js#L792

Also the way Intl detects a native implementation of defineProperty is pretty good:

https://github.com/andyearnshaw/Intl.js/blob/master/src/util.js#L3-L8

However, it is happy to use any existing implementation that can create a blank property.  If that doesn't work, it falls back to a bundled polyfill that just ignores getter definitions. Because of the likelihood of side effects, we don't do this in the general polyfill, and instead throw an error.

Possible solutions:
1. Polyfill service changes the general defineProperty polyfill to not throw if you try to define a getter or setter in an environment where that won't work. We could do something less aggressive like a console.warn (though the browser concerned probably doesn't implement `console`), but basically the effect would be that it would silently not work.  This would mirror the functionality implemented by the Intl polyfill's bundled defineProperty.
2. Intl polyfill could update its test for native defineProperty support to try and define a getter. This would (currently) cause our defineProperty polyfill to throw, and would then fall back to the more forgiving bundled dP implementation within Intl.
3. Intl polyfill could stop using accessor properties entirely.  Since they only use them very sparingly, this seems like not a massive amount of work, though given how sparingly they are used I suspect they're only used where they're essential.

/cc @caridy

**Comment by andyearnshaw** [comment] 2016-05-31 09:35
Accessors are used in Intl.js to provide as close-to-specification implementation as possible.  At least one of the getters is a performance optimisation, too, so option 3 isn't a great idea.  Another point to note is that we use the proper Ecma 402 tests from the test262 suite too, so removing accessors would cause these tests to fail.

Given that, option 2 seems like the best option, it's a minor change and should resolve this problem without any foreseeable side-affects.

Side note, not sure if it's worth mentioning—and certainly doesn't affect this this issue—but the `defineProperty` polyfill doesn't seem to account for IE8's ability to use accessors on DOM objects.  That could affect other polyfills that polyfill DOM accessors.  If this is intentional, however, then that's fine.

**Comment by caridy** [comment] 2016-05-31 15:07
Yes, I can confirm that Ecma-402 only requires a getter in 2 places, `NumberFormat.prototype.format`, and `DateTimeFormat.prototype.format`. We have decided to avoid this in the future, and therefore one of the links above (`formatToParts`) will change very soon to not use a getter.

I agree with @andyearnshaw that option 2 seems like a good place to start, I will take a stab at it, and see how it goes.

**Comment by triblondon** [comment] 2016-06-01 01:01
@andyearnshaw thanks for the pointer on DOM object accessors. I believe we already have that covered by using the native impl in IE8 when the target is a DOM object:

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/defineProperty/polyfill.js#L10

Do you think we can improve on this?

**Comment by andyearnshaw** [comment] 2016-06-01 07:54
@triblondon that covers the basics (`document`, `window` and elements) but nothing else.  That might be enough, though you could probably add a couple of others like `Event` and `Event.prototype`.  

FWIW, you can distinguish a DOM object in IE 8 by testing whether it is an instance of `Object`:

``` javascript
if (nativeDefineProperty && object && typeof object === 'object' && !(object instanceof Object)) {
    return nativeDefineProperty(object, property, descriptor);
}
```

That being said, you can't be certain because objects from other contexts have the same trait.  Still, it might be worth just letting `nativeDefineProperty` have a go in this case, as your polyfill is just going to throw an error anyway (albeit with a much better error message) and defining properties on objects from other windows seems like a rarer use case than polyfilling accessors on the obscurer DOM objects.

**Comment by triblondon** [comment] 2016-06-01 08:11
well, our polyfill _might_ throw an error - if the definition of the property includes a getter or setter.  Otherwise it would work, and therefore be better than the native version if the target is not a DOM object.  Interesting tip though - so `{} instanceOf Object` is false in IE8?  Wow.

Maybe the simplest solution is that if there's a native impl we could always try using it, wrap it in a try...catch and polyfill in the catch.  I could give that a go but it's probably not the best use of time.

Going to close this since you have an issue to update your feature detect.  When you merge the change we will pull in an update.

**Comment by triblondon** [comment] 2016-06-01 08:11
Actually on second thought we have a flag for tracking an upstream issue...

**Comment by davidpelayo** [comment] 2016-06-07 17:11
In addition, I just checked that for: [https://cdn.polyfill.io/v2/polyfill.js?flags=gated&features=Intl.~locale.it-IT](https://cdn.polyfill.io/v2/polyfill.js?flags=gated&features=Intl.~locale.it-IT) running in Safari, we get the following result:

``` javascript
/* Polyfill service v3.6.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: safari/9.1.0
 * Features requested: Intl.~locale.it-IT
 * 
 * - Intl, License: MIT (required by "Intl.~locale.it-IT")
 * - Intl.~locale.it-IT, License: MIT */

(function(undefined) {
if (!('Intl' in this)) {

// Intl
/* rest of the code */
}
```

While [the 'official' polyfill](https://github.com/andyearnshaw/Intl.js/) checks the following: 

``` javascript
var areIntlLocalesSupported = require('intl-locales-supported');

var localesMyAppSupports = [
    /* list locales here */
];

if (global.Intl) {
    // Determine if the built-in `Intl` has the locale data we need.
    if (!areIntlLocalesSupported(localesMyAppSupports)) {
        // `Intl` exists, but it doesn't have the data we need, so load the
        // polyfill and patch the constructors we need with the polyfill's.
        var IntlPolyfill    = require('intl');
        Intl.NumberFormat   = IntlPolyfill.NumberFormat;
        Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
    }
} else {
    // No `Intl`, so use and load the polyfill.
    global.Intl = require('intl');
}
```

The locale support check made the difference throwing an unexpected error, while if we remove the `gated` flag, since it's not gated anymore, the polyfill then gets loaded correctly. Therefore Safari doesn't get the exception.

**Comment by triblondon** [comment] 2016-06-08 07:54
@davidpelayo Good point, but different issue.  Please raise separately.  If you could do it in a PR that updates the detect.js file, even better!

**Comment by JakeChampion** [comment] 2016-07-28 20:14
I believe this issue can be closed now. I will create a new issue for the `detect.js` suggestion.

**Comment by triblondon** [comment] 2016-08-03 04:14
Agreed.

**Closed as completed by triblondon** 2016-08-03 04:14 UTC
