### ISSUE TITLE
Cannot use Picturefill

### ISSUE THREAD

**Issue by falconmick** [polyfillpolyfill/polyfill-service#1698] opened 2018-04-11 06:23 UTC
https://polyfill.io/v2/docs/features/#HTMLPictureElement

I am trying to utalise picture in IE11 and I cannot find what feature HTMLPictureElement is in and I cannot just get it via https://cdn.polyfill.io/v2/polyfill.js?features=HTMLPictureElement

**Comment by IamManchanda** [comment] 2018-08-26 10:36
Dupe of #1679

**Closed as completed** 2018-09-03 01:36 UTC
