### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute appendChild on Node: Only one element on document allowed.

### ISSUE THREAD

**Issue by joelfsreis** [polyfillpolyfill/polyfill-service#875] opened 2016-09-14 17:07 UTC
I did not change the code and I started to have this error on my website. I have only noticed this today

The error is in this line:
`var t, n = document.appendChild(document.createElement("body")), o = n.appendChild(document.createElement("iframe")), r = o.contentWindow.document, c = Element.prototype = r.appendChild(r.createElement("*")), d = {}, m = function(e, t) {`

**Comment by joaojeronimo** [comment] 2016-09-14 17:29
Same issue here.

Our src: `https://cdn.polyfill.io/v2/polyfill.js?features=default,Element|gated,Promise|always|gated,matchMedia,console,console.warn`

The debugger points to the Element polyfill code ([this line](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/polyfill.js#L13)).

**Comment by dpereira411** [comment] 2016-09-14 18:02
Same here :( Page is not loading because the callback is not being called.

**Comment by JakeChampion** [comment] 2016-09-14 18:13
Could you provide some more information at all? Which browser and version?
What is your polyfill.io URL? It would also be good if you could provide a
minimal test case, jsbin.com is a good place to create a test case on.

**Comment by dpereira411** [comment] 2016-09-14 18:25
This is happening in all major browsers / recent versions. The URL I'm fetching is https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,setImmediate,matchMedia&flags=always,gated&unknown=polyfill&callback=arceus_callback_1
If I fetch the same URL without .min I see its the 3.12 version on the headers. Will provide a test later.

**Comment by JakeChampion** [comment] 2016-09-14 20:23
Element polyfill shouldn't load in any major browsers, it should only load in [ie6/7/8](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/config.json#L10). I'll look into this, thanks for the report.

**Comment by JakeChampion** [comment] 2016-09-14 21:05
I found the regression -- https://github.com/Financial-Times/polyfill-service/commit/60d4a7dcf8ec761e3eeca03db690b0867b9e38c7#commitcomment-19026572

I've made a PR to revert that change -- https://github.com/Financial-Times/polyfill-service/pull/878

I've tested this url in Chrome Stable -- `/v2/polyfill.js?features=Element,Promise&flags=always,gated`

Please send any other URLs you think I should test and any browsers you want me to test. I will test as many as possible before merging that PR and releasing it to production.

**Comment by JakeChampion** [comment] 2016-09-14 21:59
I tested all the URLs mentioned in this issue across the stable desktop browsers, all work with the patch.

The PR has been merged, a patch release is being made. It will go live to QA in 10 minutes where I will test it once more before promoting it to production. I expect it hitting production at midnight UK time.

To help identify this issues before they hit production, I advice you follow our [twitter account](https://twitter.com/polyfillio/) where we announce new releases to qa (http://qa.polyfill.i)o and to production (https://polyfill.io). We release to qa and wait for at least 7 days before promoting to production as to allow our users to report any issues/regressions.

**Comment by JakeChampion** [comment] 2016-09-14 22:33
I'm testing http://qa.polyfill.io right now across as many browsers as I can before promoting to production.

My testing consists of visiting https://jsbin.com/joqoqebeve/edit?html,js,console,output and checking that an error may occur when I comment out lines 9 or 10 and that an error is not thrown when lines 12 or 13 execute.

I will update this comment with the results as I get them.
- [x] Chrome stable - _passed_
- [x] Firefox stable - _passed_
- [x] IE 11 - _passed_
- [x] IE 8 - _passed_ (jsbin.com doesn't work in IE8, have to use the output mode to test https://output.jsbin.com/joqoqebeve)
- [x] Edge 13 - _passed_
- [x] Edge 14 - _passed_
- [x] Safari stable - _passed_
- [x] Opera stable - _passed_
- [x] Yandex stable - _passed_
- [x] Android 6 - _passed_
- [x] Android 5 - _passed_
- [x] Android 4.4 - _passed_
- [x] iOS 10 - _passed_
- [x] iOS 9 - _passed_
- [x] iOS 8 - _passed_
- [x] Windows Phone 8.1 - _passed_

**Comment by JakeChampion** [comment] 2016-09-14 23:06
Latest version has been pushed to NPM and is currently being deployed to https://polyfill.io

Once it is deployed I will test on a couple of browsers and then close this ticket if they all pass.

**Comment by dpereira411** [comment] 2016-09-14 23:07
Thank you very much @JakeChampion :))

**Comment by JakeChampion** [comment] 2016-09-14 23:19
Issue looks to be resolved, closing this ticket.

**Closed as completed by JakeChampion** 2016-09-14 23:19 UTC

**Comment by joelfsreis** [comment] 2016-09-15 10:07
@JakeChampion With version 3.12.1 fixed the issue, thank you!

**Comment by joaojeronimo** [comment] 2016-09-15 10:54
Seems fixed here as well, thank you!

**Comment by rubencodes** [comment] 2016-10-13 19:05
Not sure if this is the right place for this, but I'm having this "issue" on 3.12.1 on an unknown/unsupported browser. I'm not explicitly requesting the Element polyfill, but it seems to be including it as a dependency when I have the `unknown=polyfill` flag. Is there any way to disable polyfilling of dependencies?

**Comment by chilanguito** [comment] 2018-10-11 17:51
Hi
