### ISSUE TITLE
[feature-request] Conditionally inject the script tag only if a feature is missing

### ISSUE THREAD

**Issue by dorongutman** [polyfillpolyfill/polyfill-service#2263] opened 2020-06-08 09:06 UTC
## What
Provide a small JS snippet that checks whether one of the requested features is missing in the browser and only then inject the script tag that fetches the polyfill.

## Details

Most of the loads of our (and probably everyone) sites are done using normal, updated browsers, that already contain the various features we use. 
The polyfill.io script we add is just to support old browsers.

However, the http request that is being made to bring the (usually empty) polyfills from polyfill.io happens to everyone.

I'd like to request that when I choose the polyfills I want, instead of getting a <script> tag, I'll get a small JS snippet that checks whether any of the features I asked is missing, and only if one of them is missing in this browser, inject the <script> tag.

Something like this (assuming I chose Promise and Array.prototype.forEach):
```js
if (!window.Promise || !Array.prototype.forEach) {
      var e = document.createElement('script');
      e.src = 'https://polyfill.io/v3/polyfill.min.js?features=Promise%2CArray.prototype.forEach';
      document.getElementsByTagName('head')[0].appendChild(e);
}
```

**Comment by JakeChampion** [comment] 2020-06-08 10:36
Closing this issue as I believe it is a duplicate of https://github.com/Financial-Times/polyfill-library/issues/111

**Closed as completed by JakeChampion** 2020-06-08 10:36 UTC
Labels: service
