### ISSUE TITLE
Intl polyfill concatenation with Intl locale data polyfill causing syntax errors

### ISSUE THREAD

**Issue by egoldblum** [polyfillpolyfill/polyfill-service#822] opened 2016-08-10 04:51 UTC
We noticed a large increase in errors right around UTC midnight today in safari when polyfilling `Intl` alongside `Intl.~locale.es` and `Intl.~locale.en`.

The problematic combined file can be fetched with the following.

```
curl 'https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl|always,Intl.~locale.en|always,Intl.~locale.es|always&unknown=polyfill' 'Accept-Encoding: gzip, deflate, sdch, br' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 
```

Not sure if this a polyfill-service bug or a bug in the polyfill itself ( https://github.com/andyearnshaw/Intl.js), but it looks like concatenation of https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.min.js#L3 with additional files causes a syntax error in safari.

https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.min.js#L3 does not have a trailing newline and it does not appear that the polyfill-service concatenation enforces that joined files exist on new lines.

We were able to work around by splitting the concatenated request into separate requests, but this is obviously not ideal from a performance perspective.

**Comment by triblondon** [comment] 2016-08-10 05:07
@egoldblum thanks for raising this.  We noticed this problem and have a fix ready:

https://github.com/Financial-Times/polyfill-service/pull/821

It is currently slated for 3.10.  In the meantime an effective workaround is to use non-minified polyfills (ie remove the `.min` from the URL).  @JakeChampion can we push this fix as a 3.9.1 patch?

**Comment by egoldblum** [comment] 2016-08-10 05:21
@triblondon thanks for the quick response and sorry I missed that earlier issue before filing this one!

**Comment by JakeChampion** [comment] 2016-08-10 08:16
This looks to be a duplicate of #820

**Closed as completed** 2016-08-10 08:21 UTC
